# Generated by Django 4.2.2 on 2023-08-01 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalApp', '0002_petstore_delete_petnew'),
    ]

    operations = [
        migrations.AddField(
            model_name='petstore',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
